### ISSUE TITLE
Unsupported constraint

### ISSUE THREAD

**Issue by JoanEspasa** [PatrickTrentin88/fzn2omt#5]
Good morning,

I have a set of instances translated to fzn and a considerable amount of them use the constraint `all_different_int`. When running through fzn2optimathsat or fzn2z3 I get the following error:

`error: constraint 'all_different_int' is not supported.`

I found that the standard decomposition of it would be: 

```predicate all_different_int(array[int] of var int:x)=forall(i,j in index_set(x) where i < j)(x[i] != x[j]);```

would it be possible the decomposition to be implemented? 

I attach one problem with it for convenience. Many thanks in advance :)

[20.fzn.txt](https://github.com/PatrickTrentin88/fzn2omt/files/4486516/20.fzn.txt)

**Comment by PatrickTrentin88** [comment]
@JoanEspasa `all_different_int` is a type-specialization of the global constraint `all_different`. This constraint is normally decomposed by the `mzn2fzn` compilation when using the standard definitions, **e.g.**  (file `all_different_int.mzn`)

```
%-----------------------------------------------------------------------------%
% Constrains the array of objects 'x' to be all different.
%-----------------------------------------------------------------------------%

predicate all_different_int(array[int] of var int: x) =
    forall(i,j in index_set(x) where i < j) ( x[i] != x[j] );
```

When it is not decomposed, it means that one is not using the `std` compilation.

---

As far as I know, several FlatZinc solvers (e.g. `choco`, `chuffed`, `gecode`, `hcsp` and `jacop`) either prepend or append the solver name to their own redefinition of the global constraints. This is also the convention adopted by [`OptiMathSAT`](http://optimathsat.disi.unitn.it/):

```
%-----------------------------------------------------------------------------%
% Constrains the array of objects 'x' to be all different.
%-----------------------------------------------------------------------------%

predicate all_different_int(array[int] of var int: x) =
    optimathsat_all_different_int(x);

predicate optimathsat_all_different_int(array[int] of var int: x);
```

So `all_different_int` is not supported because the solver expects `optimathsat_all_different_int` instead.

The package containing the redefinition of global constraints for [`OptiMathSAT`](http://optimathsat.disi.unitn.it/) is available [here](http://optimathsat.disi.unitn.it/data/smt2.tar.gz). The package must be unzipped in:

- `${MINIZINC_PATH}/lib/minizinc` for MiniZinc version 1.X
- `${MINIZINC_PATH}/share/minizinc` for MiniZinc version 2.X

Then it can be used with:

```
~$ mzn2fzn -G smt2 model_file.mzn [data_file.dzn] \
		-o output_file.fzn
```

Alternatively, one can also use the [**emzn2fzn** compiler](https://github.com/PatrickTrentin88/emzn2fzn).

At the moment, there doesn't appear to be any performance advantage in using the `smt2` translation. Hence, my advice is to translate the MiniZinc models with the `std` directory of global constraints.

Is there any reason why you appear not be doing that already?

**Comment by JoanEspasa** [comment]
Hmmm I see  ... I'm not that knoweledgeable about the minizinc pipeline, sorry. We are using another tool that outputs flatzinc called [Savile Row](https://savilerow.cs.st-andrews.ac.uk/index.html) , which can (amongst others) output mzn, or fzn for chuffed or gecode from Essence prime models.

**Comment by PatrickTrentin88** [comment]
@JoanEspasa 

> Hmmm I see ... I'm not that knoweledgeable about the minizinc pipeline, sorry. We are using another tool that outputs flatzinc called [Savile Row](https://savilerow.cs.st-andrews.ac.uk/index.html) , which can (amongst others) output mzn, or fzn for chuffed or gecode from Essence prime models.

From a quick test, it looks like it supports the FlatZinc flavor of `chuffed` and `gecode` only.

However, one can use it to generate a MiniZinc model and then compile the latter with `mzn2fzn` to a FlatZinc model for any target FlatZinc solver, including `OptiMathSAT`. This costs just a bit extra overhead.

Every FlatZinc solver is required to support models compiled with the `std` library. It is a bit mysterious the reason why they have chosen to provide special support for Chuffed and Gecode, rather than all other tools.
